apiVersion: v1
kind: ServiceAccount
metadata:
  name: kong-serviceaccount
  namespace: kong
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kong-leader-election
  namespace: kong
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-admin
  namespace: kong
spec:
  ports:
  - name: admin
    port: 80
    protocol: TCP
    targetPort: 8001
  - name: admin-ssl
    port: 443
    protocol: TCP
    targetPort: 8444
  selector:
    app: kong-cp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-manager
  namespace: kong
spec:
  ports:
  - name: manager
    port: 80
    protocol: TCP
    targetPort: 8002
  - name: manager-ssl
    port: 443
    protocol: TCP
    targetPort: 8445
  selector:
    app: kong-cp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-devportal
  namespace: kong
spec:
  ports:
  - name: portal
    port: 80
    protocol: TCP
    targetPort: 8003
  - name: portal-ssl
    port: 443
    protocol: TCP
    targetPort: 8446
  selector:
    app: kong-cp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-devportal-api
  namespace: kong
spec:
  ports:
  - name: portal-api
    port: 80
    protocol: TCP
    targetPort: 8004
  - name: portal-api-ssl
    port: 443
    protocol: TCP
    targetPort: 8447
  selector:
    app: kong-cp
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: kong-cluster-hybrid
  namespace: kong
spec:
  ports:
  - name: cluster
    port: 8005
    protocol: TCP
    targetPort: 8005
  - name: cluster-telemetry
    port: 8006
    protocol: TCP
    targetPort: 8006
  selector:
    app: kong-cp
  type: NodePort
---
#------------------------------------------------------------------------------
# Deployment: Kong Control Plane
#------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kong-cp
  name: kong-cp
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-cp
  template:
    metadata:
      labels:
        app: kong-cp
    spec:
      automountServiceAccountToken: false
      containers:
      - name: kong-cp
        env:
        - name: KONG_LICENSE_DATA
          valueFrom:
            secretKeyRef:
              key: license
              name: kong-enterprise-license
        - name: KONG_ROLE
          value: control_plane
        - name: KONG_CLUSTER_CERT
          value: /usr/local/kong/cluster_key/tls.crt
        - name: KONG_CLUSTER_CERT_KEY
          value: /usr/local/kong/cluster_key/tls.key
        - name: KONG_PROXY_LISTEN
          value: "off"
        - name: KONG_STATUS_LISTEN
          value: 0.0.0.0:8100
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001 reuseport backlog=16384, 0.0.0.0:8444 http2 ssl reuseport backlog=16384
        - name: KONG_ADMIN_GUI_AUTH
          value: "basic-auth"
        - name: KONG_ADMIN_GUI_SESSION_CONF
          value: "{\"cookie_name\":\"admin_session\",\"cookie_samesite\":\"off\",\"secret\":\"kong-manager\",\"cookie_secure\":false,\"storage\":\"kong\"}"
        - name: KONG_ENFORCE_RBAC
          value: "on"
        - name: KONG_PORTAL
          value: "on"
        - name: KONG_PORTAL_AUTH
          value: "basic-auth"
        - name: KONG_PORTAL_SESSION_CONF
          value: "{\"storage\":\"kong\",\"cookie_name\":\"portal_session\",\"cookie_samesite\":\"off\",\"cookie_domain\":\".client.net\",\"cookie_samesite\":\"off\",\"secret\":\"super-secret\",\"cookie_secure\":false}"
        - name: KONG_PROXY_URL
          value: http://kong-proxy.bpce.pt
        - name: KONG_ADMIN_API_URI
          value: http://kong-admin.bpce.pt
        - name: KONG_ADMIN_GUI_URL
          value: http://kong-manager.bpce.pt
        - name: KONG_PORTAL_GUI_HOST
          value: kong-devportal.bpce.pt
        - name: KONG_PORTAL_API_URL
          value: http://kong-devportal-api.bpce.pt
        - name: KONG_PORTAL_GUI_PROTOCOL 
          value: http
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "postgres"
        - name: KONG_PG_USER
          value: "kong"
        - name: KONG_PG_PASSWORD
          value: "kongpass"
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        image: kong/kong-gateway:latest
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - kong quit
        ports:
        name: kong-cp
        ports:
        - containerPort: 8001
          name: admin
          protocol: TCP
        - containerPort: 8002
          name: manager
          protocol: TCP
        - containerPort: 8003
          name: devportal
          protocol: TCP
        - containerPort: 8004
          name: portalapi
          protocol: TCP
        - containerPort: 8005
          name: cluster
          protocol: TCP
        - containerPort: 8006
          name: telemetry
          protocol: TCP
        - containerPort: 8444
          name: admin-ssl
          protocol: TCP
        - containerPort: 8445
          name: manager-ssl
          protocol: TCP
        - containerPort: 8446
          name: devportal-ssl
          protocol: TCP
        - containerPort: 8447
          name: portalapi-ssl
          protocol: TCP
        - containerPort: 8100
          name: metrics
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: kong-cp
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /status
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - name: cluster-key
          mountPath: "/usr/local/kong/cluster_key"
          readOnly: true
      volumes:
        - name: cluster-key
          secret:
            secretName: secret-hybrid-cluster-tls
            optional: false # default setting; "secret-tls" must exist
